### PR TITLE
Developer mode - group 7

### PR DESCRIPTION
**Pull request by avipotter33**
**Submitted by** Itay Hofshy, Avia Izakovitch, Gavriel Fernanadez.

We created a developer mode which contains a few features that will help the developer debug his code and work on his code. In this mode you would find:
A pause button - allows the player to stop the game, check his code (or for any other reason), and then continue the same game. In addition, it allows the developer to track the movement of his car frame by frame - stop after each movement and understand why and how it happened.
A dash board, which shows the action the server recieved, and the delay between the beginning of the driver's code and the receivement of the action. This dashboard will help the developer keep track of his code while the game is running, and also spot if a mistake happened beacuse of a problem in the code, or beacuse of a connection problem to the server.

**Screenshots:**
WhatsApp Image 2023-08-10 at 09 18 14
צילום מסך 2023-08-10 091416

### CODE REVIEW

**Comment by yaacov** [comment]
@sleviim hi, please review.

**Comment by yaacov** [comment]
@avipotter33 hi,

can you add screenshots of the feature ( before "Play" / after "Music" ) ?
can you update the PR description to include why it's needed to change the button from "Play" to "Music" ?

**Comment by sleviim** [comment]
@yaacov 
Thanks for the PR and the screenshots.
If it's not too much trouble, please generate a new "after" screenshot without the "Fun" button.
Other than that - looks good :)

**Comment by sleviim** [comment]
I think you also uploaded the change for your feature
(The changed  files not only deal with the "Play" wording as before)

**Comment by itayfree** [comment]
@sleviim hi, this is the wrong PR, the one with the "Music" is #470

**Pull request closed without merging**
