### PR TITLE
modifying obstacles generator

### PR DESCRIPTION
**Pull request by yodem**
solving issue: Fair obstacle generation #131 

Signed-off-by: yodem yotamfromm123@gmail.com

### CODE REVIEW

**Comment by emesika** [comment]
Don't you think that this will make the game less attractive having all lanes with the same obstacles in each second ???
Please elaborate

**Comment by yodem** [comment]
I do think it will make the game less attractive but in the issue #131 Nir says that one of the solutions is 
to generate the same sequence of obstacles so this way it will be 100% fair with no posibility that the person with the better code to lose.

**Comment by emesika** [comment]
Yet, I think that it can be the same sequence but in random order

**Comment by yodem** [comment]
what do you mean

**Comment by emesika** [comment]
If you have players p1and p2 and obstacles x, y and z then p1 may have obstacles z , x and y and p2 may have x, y and z , it will be same set of obstacles but not in the same order

**Comment by nirs** [comment]
Let support all 3 - the current method, getting same obstacles in random cell, getting same obstacle in same cells, and having same obstacles in different order.

Les have an ObstacleGenerator object, with 3 implementations. We will specify the name of the class in the config, or in a command line parameter.

What do you think?

**Comment by nirs** [comment]
Yodem, please explain in the commit message the motivation for the change and how the change is solving the issue. "modifying obstacle generator" is not helpful to understand your change.

**Comment by emesika** [comment]
+1 for Nir's 3 methods suggestion

**Comment by nirs** [comment]
Closing for now, I don't think this is solve a real issue.

**Pull request closed without merging**
