### PR TITLE
solution for #113 issue, life calculation

### PR DESCRIPTION
**Pull request by yodem**
issue - Life calculations should be change when driving not in your lane #113 solved
random driver hasn't changed
In the rose/common/config.py I added a veriable which supposed to lower the score by 20 when the player or when the car is not in his lane.
At the server/player.py code, I added a function which calculate the boundaries of the lane and returns a True value when the player not in his lane.
At the score code I used the move_extra_backwards, so it will punish the player by extra 10.

### CODE REVIEW

**Comment by nirs** [comment]
Yodem, I think we should make a more generic change. Instead of adding special movement when you are not in your lane, punish the driver by giving half of the score or double the backward movement.

**Comment by yodem** [comment]
Ok, I will work on these 12 comments in sunday :) but thank you.

**Comment by bronhaim** [comment]
+1 from my side. Eli, Nir - please take a look. It's simple and clean

**Comment by nirs** [comment]
This pull request seems out of date. Please close it and submit a new one.

**Pull request closed without merging**
