### PR TITLE
Add few more changes to the linux_intro presentation

### PR DESCRIPTION
**Pull request by sleviim**
- Use <br> to break long paragraph sentences.
- Use <b> for emphasizing directories names (also in the exercise).
- Change some capital/small letters as needed.
- Remove the sl example from sudo dnf install.

@shiramax, please approve

### CODE REVIEW

**Comment by sleviim** [comment]
Ping @shiramax 
Also, I'd like to hear your thoughts, @rollandf

**Comment by rollandf** [comment]
:+1:

**Review by shiramax — APPROVED** [review]

**Comment by shiramax** [comment]
@sleviim @rollandf looks good to me,  thanks!

**Comment by rollandf** [comment]
:doughnut:

**Pull request merged**
