### PR TITLE
Web admin: change game rate from the web intreface

### PR DESCRIPTION
**Pull request by nirs**
These patches expose the server game rate in the web interface and allow changing the rate with a single click.

The web interface is still raw html, I will add basic CSS in the next patches.

@emesika, @bronhaim, please review.

### CODE REVIEW

**Comment by nirs** [comment]
Here is a short demo: https://youtu.be/1iJlssKHBw4

**Comment by nirs** [comment]
@rollandf can you review?

**Comment by rollandf** [comment]
👍

**Comment by rollandf** [comment]
👍

**Pull request merged**
