### PR TITLE
Classroom api

### PR DESCRIPTION
**Pull request by AnnaDinaburgVulikh**
Hi @shiramax ,
I have created a first step for automating classroom use.
The current version can:
1. Create a new classroom  
2. Add a student list (using csv file)
3. Add a teacher list (using csv file)
4. Retrieve class list with class ID.

It also includes an email address validation, where only '@gmail.com' is allowed.

### CODE REVIEW

**Comment by AnnaDinaburgVulikh** [comment]
Hi @shiramax , any comments?

**Comment by shiramax** [comment]
@AnnaDinaburgVulikh code wise looks good, I will test this PR as soon as possible. thanks for your contribution!

**Comment by AnnaDinaburgVulikh** [comment]
Hi @shiramax , updated the commands for the course creation and changed the syntax from 'class' to 'course' as is addressed by the API.
The changes are a starting point for the next PR that is going to include Topics and Assignments handling.

**Review by shiramax — CHANGES_REQUESTED** [review]
Looks great! and working great!
I have small nitpicks and this is ready to be merged, well done!

**Comment by AnnaDinaburgVulikh** [comment]
Hi @shiramax , thanks for the review.
Fixed the requested changes.
The travic-ci failed on playing some videos. They seem to work just fine, not sure what the problem is.

**Pull request merged**
